#!/usr/bin/bash

if [ -d "dist/" ]; then
    
    ##echo "deleting dist/ directory"
    ##rm -r dist/
    ##echo "done\n"
    echo "going to dist/"
    cd dist/
    for dir in */; do
        if [ "$dir" != "node_modules/" ]; then
            echo "deleting $dir"
            rm -r $dir
        fi
    done
    for file in *; do
        
        if [[ -f "$file" ]]; then
            echo "deleting $file"
            rm $file
        fi
    done
    echo "going back .."
    cd ..    
    echo ""
fi


for dir in */; do
    if [ "$dir" != "dist/" ] && [ "$dir" != "node_modules/" ]; then
        echo "copying recursively $dir into dist/$dir"
        cp -r $dir dist/$dir
        echo "done\n"
    fi
done

for file in `ls -a`; do 
    if [[ -f "$file" && "$file" != "package.json" ]]; then
        echo "copying $file into dist/"
        cp $file dist/
        echo "done\n"
    fi 
done

echo "going to dist"
cd dist
mv npackage.json package.json

echo "doing change in dist"
rm -r Scripts
rm -r public/api
rm app.ts
rm dirname.ts
echo "done\n"
cd ..
echo "done\n"

echo "running npm run build"
npm run build 
echo "done\n"

echo "going to dist"
cd dist

rm "tsconfig.json"

echo "running node app.js"
node app.js

echo "all done"
